name: Run Python Script

on:
  push:
    branches:
      - main # 指定在推送到 main 分支时触发

jobs:
  run-script:
    runs-on: ubuntu-latest # 指定运行环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # 检出代码

      - name: Set up Python
        uses: actions/setup-python@v2 # 设置 Python 环境
        with:
          python-version: '3.8' # 指定 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv  # 安装依赖

      - name: Run script
        env:
          USERNAME: ${{ secrets.GITHUB_USERNAME }} # 设置环境变量
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python main.py  # 执行脚本
