name: Run Python Script and Log Results

on:
  schedule:
    - cron: '0 */8 * * *' # 每12小时执行一次，于每小时的0分钟

jobs:
  run-and-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }} # 使用个人访问令牌进行检出

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run script and save logs
        env:
          PYTHONUNBUFFERED: 1
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          python main.py

      - name: Commit logs
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add logs/*
          # 创建一个时间戳
          TIMESTAMP=$(date +'%Y-%m-%d-%H-%M-%S')
          # 使用时间戳创建提交消息
          git commit -m "Fork-log-$TIMESTAMP"
          git push
        env:
          PYTHONUNBUFFERED: 1
          GIT_ASKPASS: echo ${{ secrets.TOKEN }}
