name: Auto Fork Workflow

on:
  push:
    branches:
      - main

jobs:
  auto-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run the auto fork script and capture output
        id: script_run
        run: |
          OUTPUT=$(python main.py | sed 's/[^a-zA-Z0-9 ]//g')
          echo "::set-output name=log_output::$OUTPUT"

      - name: Always commit and push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: bearer ${{ secrets.GITHUB_TOKEN }}"
          BRANCH_NAME="fork-log-$(date +'%Y-%m-%d-%H-%M-%S')"
          git checkout -b "$BRANCH_NAME"
          COMMIT_MESSAGE="${{ steps.script_run.outputs.log_output }}"
          git commit --allow-empty -am "$COMMIT_MESSAGE"
          git push origin "$BRANCH_NAME"
          echo "Pushed changes to $BRANCH_NAME."
