name: Run Python Script and Log Results

on:
  push:
    branches:
      - main

jobs:
  run-and-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }} # 使用个人访问令牌进行检出

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run script and save logs
        env:
          PYTHONUNBUFFERED: 1
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          python main.py

      - name: Commit logs
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add logs/*
          git commit -m "Added execution logs"
          git push
        env:
          PYTHONUNBUFFERED: 1
          GIT_ASKPASS: echo ${{ secrets.TOKEN }}
